Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    # path('products/', include('products.urls')),

    path('signup/', user_views.register_page, name='register'),
    path('login/', user_views.login_page, name='login'),
    path('logout/', user_views.logout_user, name='logout'),

    path('password-change/', user_views.password_change, name='password_change'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.customer_products_view, name='customer-products-view'),
    path('product-details/<int:pk>/', views.customer_product_details, name='customer-product-details'),
    path('orders/', views.customer_order, name='customer-order'),

    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.update_item, name='update_item'),
    path('process_order/', views.process_order, name='process_order'),

    path('profile/', views.profile, name='profile'),

    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('inbox/', views.admin_inbox, name='inbox'),
    path('message/<str:pk>/', views.message_page, name='message'),
    path('send-feedback/', views.send_feedback, name='send-feedback'),
    path('feedbacks/', views.view_feedback, name='feedbacks'),

    path('admin-dashboard/', views.admin_dashboard, name='admin-dashboard'),

    path('view-customer/', views.admin_customer_view, name='admin-view-customer'),
    path('delete-customer/<str:username>/', views.admin_customer_delete, name='admin-delete-customer'),

    path('customer-orders/', views.admin_customer_order_view, name='admin-customer-order-view'),
    path('customer-order-update/<str:pk>/', views.admin_customer_order_update, name='admin-customer-order-update'),
    path('customer-order-delete/<str:pk>/', views.admin_customer_order_delete, name='admin-customer-order-delete'),

    path('admin-products/', views.admin_products_view, name='admin-products-view'),
    path('add-product', views.admin_add_product, name='add-product'),
    path('admin-product-details/<int:pk>/', views.admin_product_details, name='admin-product-details'),
    path('update-product/<int:pk>/', views.admin_update_product, name='update-product'),
    path('delete-product/<int:pk>/', views.admin_delete_product, name='delete-product'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255, null=True)
    mobile = models.CharField(max_length=100, null=True)
    profile_pic = models.ImageField(default='users/blank-profile-picture.png', upload_to='users')

    def __str__(self):
        return f'{self.user}'

    @property
    def get_name(self):
        return self.user.first_name + " " + self.user.last_name


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Product(models.Model):
    name = models.CharField(max_length=255, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    description = models.TextField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    featured = models.BooleanField(default=False)
    image = models.ImageField(upload_to='store', default='store/placeholder.png', null=True, blank=True)
    tags = models.ForeignKey(Tag, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    class Meta:
        ordering = ['tags', 'name']


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Order Confirmed', 'Order Confirmed'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered'),
    )

    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    date_ordered = models.DateTimeField(default=timezone.now, null=True)
    status = models.CharField(choices=STATUS, default='Pending', max_length=200, null=True)
    complete = models.BooleanField(default=False, blank=False, null=True)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f'{self.customer}'

    @property
    def get_cart_total(self):  # calculates overall total price
        order_items = self.orderitem_set.all()
        total = sum([item.get_total for item in order_items])
        return total

    @property
    def get_cart_items(self):  # calculates overall total items
        order_items = self.orderitem_set.all()
        total = sum([item.quantity for item in order_items])
        return total

    class Meta:
        ordering = ['-date_ordered']


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product)

    @property
    def get_total(self):  # calculates individual total price
        total = self.product.price * self.quantity
        return total

    class Meta:
        ordering = ['-date_added']


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    mobile = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    division = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.address


class Contact(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=300)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}, {self.email} at {self.created}'

    class Meta:
        ordering = ['is_read', '-created']


class Feedback(models.Model):
    name = models.CharField(max_length=255)
    feedback = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

store/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Customer, Contact, Feedback, Product, Order, ShippingAddress


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(label='Email Address')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'First Name', 'last_name': 'Last Name'}


class CustomerUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        labels = {'profile_pic': 'Profile Picture'}
        exclude = ['user']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'tags', 'description', 'digital', 'featured', 'image']
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control mt-1', 'rows': 6}),
        }

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['tags'].empty_label = 'Select Category'


class OrderStatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['customer', 'date_ordered', 'transaction_id', 'status']
        # widgets = {
        #     'customer': forms.TextInput(attrs={'disabled': 'True'}),
        #     'date_ordered': forms.TextInput(attrs={'disabled': 'True'}),
        #     'transaction_id': forms.TextInput(attrs={'disabled': 'True'}),
        # }

    def __init__(self, *args, **kwargs):
        super(OrderStatusForm, self).__init__(*args, **kwargs)
        self.fields['status'].empty_label = 'Change Order Status'


class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = '__all__'
        exclude = ['customer', 'order', 'date_added']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'First Name*'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Last Name*'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Mobile*'}),
            'email': forms.EmailInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Email*'}),
            'address': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Address*'}),
            'city': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'City*'}),
            'division': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Division*'}),
        }


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'feedback']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mt-1'}),
            'feedback': forms.Textarea(attrs={'class': 'form-control mt-1', 'rows': 6}),
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Your Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control mt-1', 'placeholder': 'name@example.com'}),
            'subject': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'class': 'form-control mt-1', 'placeholder': 'Message',
                                             'rows': 6}),
        }

store/templates/store/about.html
{% extends 'store/base.html' %}
{% load static %}

{% block body %}
<br>
<div class="row my-4 justify-content-center">
    <div class="col-md-6">
        <div class="card card-body">
            <div class="mb-3 fs-4 alert alert-info text-center">
                    <strong>About</strong>
            </div>
            <p class="text-center fs-4">Love to learn and still learning stuffs.</p>
        </div>
    </div>
</div>
{% endblock body %}

store/templates/store/admin_customer_order_view.html
{% extends 'store/base.html' %}
{% block orderactive %} active {% endblock orderactive %}

{% block body %}
<br>
<div class="row my-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    {% if orders %}
    <div class="box-element shadow mb-4">
        <div class="d-flex justify-content-between">
            <strong class="fs-3">All Bookings</strong>
            <form class="d-flex w-50" method="get">
                <div class="input-group">
                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                    <input class="form-control me-2" type="search" name="q" aria-label="Search"
                           placeholder="Search order using transaction id">
                </div>
                <button class="btn btn-outline-info" type="submit">Search</button>
            </form>
        </div>
        <hr>

        <table class="table table-striped table-hover border">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Customer</th>
                <th scope="col">Date Ordered</th>
                <th scope="col">Products</th>
                <th scope="col">Transaction Id</th>
                <th scope="col">Address</th>
                <th scope="col">Order Status</th>
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
            </tr>

            {% for order in orders %}
            <tr>
                <td><strong>{{ forloop.counter }}.</strong></td>
                <td>{{ order.customer }}</td>
                <td>{{ order.date_ordered }}</td>
                <td>
                    {% for item in order.orderitem_set.all %}
                        <p>{{ forloop.counter }}. {{ item.product.name }}, Unit Price: {{ item.product.price }}/=,
                            Qty: x{{ item.quantity }}</p>
                    {% endfor %}
                </td>
                <td>{{ order.transaction_id }}</td>
                <td>
                    {% for address in order.shippingaddress_set.all %}
                        {{ address.address }}, {{ address.city }}, {{ address.division }}
                    {% endfor %}
                </td>
                <td>
                    {% if order.status == 'Pending' %}
                        <span class="text-danger"><strong>{{ order.status }}</strong></span>
                    {% elif order.status == 'Order Confirmed' %}
                        <span class="text-success"><strong>{{ order.status }}</strong></span>
                    {% elif order.status == 'Out for delivery' %}
                        <span class="text-warning"><strong>{{ order.status }}</strong></span>
                    {% elif order.status == 'Delivered' %}
                        <span class="text-primary"><strong>{{ order.status }}</strong></span>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'admin-customer-order-update' order.id %}"
                       class="btn btn-primary btn-sm {% if order.status == 'Delivered' %} disabled {% endif %}">
                        <i class="fas fa-edit"></i></a>
                </td>
                <td>
                    <a href="{% url 'admin-customer-order-delete' order.id %}" class="btn btn-danger btn-sm">
                        <i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
    <div class="box-element shadow mb-4">
        <p class="text-center"><strong class="fs-3">No orders found!!!</strong></p>
    </div>
    {% endif %}
</div>

{% endblock body %}

store/templates/store/admin_dashboard.html
{% extends 'store/base.html' %}
{% block adminactive %} active {% endblock adminactive %}
{% load static %}

{% block body %}
<br>
<div class="row my-4">
    <div class="col-4">
        <div class="col-md">
            <div class="card text-center text-white mb-3 shadow" id="total-customers">
                <div class="card-header">
                    <h4 class="card-title">Total Customers</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_customers }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col-4">
        <div class="col-md">
            <div class="card text-center text-white mb-3 shadow" id="total-products">
                <div class="card-header">
                    <h4 class="card-title">Total Products</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_products }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'store/status.html' %}

<br>
<div class="row my-4">
    {% if recent_orders %}
    <div class="box-element shadow mb-4">
        <p><strong class="fs-3">Recent Orders</strong></p>
        <hr>

        <table class="table table-striped table-hover border">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Customer</th>
                <th scope="col">Date Ordered</th>
                <th scope="col">Transaction Id</th>
                <th scope="col">Address</th>
                <th scope="col">Order Status</th>
            </tr>

            {% for order in recent_orders %}
            <tr>
                <td><strong>{{ forloop.counter }}.</strong></td>
                <td>{{ order.customer }}</td>
                <td>{{ order.date_ordered }}</td>
                <td>{{ order.transaction_id }}</td>
                <td>
                    {% for address in order.shippingaddress_set.all %}
                        {{ address.address }}, {{ address.city }}, {{ address.division }}
                    {% endfor %}
                </td>
                <td>
                    {% if order.status == 'Pending' %}
                        <span class="text-danger"><strong>{{ order.status }}</strong></span>
                    {% elif order.status == 'Order Confirmed' %}
                        <span class="text-success"><strong>{{ order.status }}</strong></span>
                    {% elif order.status == 'Out for delivery' %}
                        <span class="text-warning"><strong>{{ order.status }}</strong></span>
                    {% elif order.status == 'Delivered' %}
                        <span class="text-primary"><strong>{{ order.status }}</strong></span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
    <div class="box-element shadow mb-4">
        <p class="text-center"><strong class="fs-3">No Recent Orders!!!</strong></p>
    </div>
    {% endif %}
</div>


{% endblock body %}

store/templates/store/admin_inbox.html
{% extends 'store/base.html' %}
{% block messagesactive %} active {% endblock messagesactive %}
{% load static %}

{% block body %}
<br>
<div class="row my-4 justify-content-center">
    <div class="col-md-8">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        <div class="box-element shadow mb-4">

            <table class="table table-info table-striped table-hover border">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Sender</th>
                        <th scope="col">Subject</th>
                        <th scope="col">Data Sent</th>
                    </tr>
                </thead>
                <tbody>
                    {% for message in inbox %}
                        {% if message.is_read %}
                    <tr>
                        {% else %}
                    <tr style="font-weight: 700;">
                        {% endif %}
                        <td>{{ forloop.counter }}.</td>
                        <td>{{ message.name }}</td>
                        <td><a href="{% url 'message' message.id %}" class="text-decoration-none">
                            {{ message.subject }}</a></td>
                        <td>{{ message.created }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>

    </div>
</div>
{% endblock body %}

store/templates/store/admin_product_details.html
{% extends 'store/base.html' %}

{% block body %}
<br>
<div class="row mt-4">
    <div class="mb-4">
        <a href="{% url 'admin-products-view' %}" class="btn btn-secondary">&laquo; Back to products</a>
    </div>
</div>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

<div class="row my-4 justify-content-center">
    <div class="col-md-5">
        <img src="{{ product.image.url }}" alt="Profile Pic" style="max-width: 400px;">
    </div>

    <div class="col-md-7">
        <h1 class="product-title">{{ product.name }}</h1>

        <span class="product-price">Price: <strong>{{ product.price|floatformat:2 }}/=</strong></span>
        <div class="product-details">{{ product.description|safe }}</div>
    </div>
</div>
{% endblock body %}

store/templates/store/admin_product_form.html
{% extends 'store/base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<br>
<div class="row my-4 justify-content-center">
    <div class="col-md-6">
        <div class="card card-body">
            <div class="mb-3 fs-4 text-center">
                <strong>{{ section_title }}</strong>
                <hr>
            </div>

            <form method="post"> {% csrf_token %}
                {{ form|crispy }}

                <div class="text-center">
                    <button class="btn btn-info mt-2" type="submit">{{ button_name }} Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

store/templates/store/admin_products_view.html
{% extends 'store/base.html' %}
{% load crispy_forms_tags %}
{% block productsactive %} active {% endblock productsactive %}

{% block body %}
<br>
<div class="row my-4 justify-content-center">
    <div class="col-md-9">
        <form id="searchForm" method="GET" class="p-4 bg-light border shadow-sm">
            {{ my_filter.form|crispy }}

            <input class="btn btn-outline-primary mt-2" type="submit" value="Search">
        </form>
    </div>
</div>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

<br>
<div class="row mb-4 justify-content-center">
    <div class="box-element shadow mb-4">
        <div class="mb-4 fs-2">
            <strong>Products</strong>
            <hr>
        </div>

        <table class="table table-striped table-hover border">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Image</th>
                <th scope="col">Category</th>
                <th scope="col">Price</th>
                <th scope="col">Featured</th>
                <th scope="col">Digital</th>
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
            </tr>

            {% for product in products %}
            <tr>
                <td><strong>{{ forloop.counter }}.</strong></td>
                <td><a href="{% url 'admin-product-details' product.id %}" class="text-decoration-none text-dark">
                    <strong>{{ product.name }}</strong></a></td>
                <td><img src="{{ product.image.url }}" alt="Profile Pic" height="40px" width="40px"/></td>
                <td>{{ product.tags }}</td>
                <td>{{ product.price|floatformat:2 }}/=</td>
                <td>{{ product.featured }}</td>
                <td>{{ product.digital }}</td>
                <td><a href="{% url 'update-product' product.id %}" class="btn btn-primary btn-sm">
                    <i class="fas fa-edit"></i></a></td>
                <td><a href="{% url 'delete-product' product.id %}" class="btn btn-danger btn-sm">
                    <i class="fas fa-trash-alt"></i></a></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="8" class="text-center"><h3>No Products Found</h3></td>
            </tr>
            {% endfor %}
        </table>

    </div>
</div>

<!-- add product floating button -->
<a href="{% url 'add-product' %}" class="float">
    <i class="fa fa-plus my-float"></i>
</a>

{% endblock body %}

store/templates/store/customer_product_details.html
{% extends 'store/base.html' %}

{% block body %}
<br>
<div class="row mt-4">
    <div class="mb-4">
        <a href="{% url 'customer-products-view' %}" class="btn btn-secondary">&laquo; Back to products</a>
    </div>
</div>

<div class="row my-4 justify-content-center">
    <div class="col-md-5">
        <img src="{{ product.image.url }}" alt="Profile Pic" style="max-width: 400px;">
    </div>

    <div class="col-md-7">
        <h1 class="product-title">{{ product.name }}</h1>

        <span class="product-price">Price: <strong>{{ product.price|floatformat:2 }}/=</strong></span>
        <div class="product-details">{{ product.description|safe }}</div>
        <div class="mt-4">
            <button class="btn btn-info add-btn update-cart" data-product="{{ product.id }}"
                    data-action="add"><i class="fas fa-cart-plus me-3"></i>Add to Cart
            </button>
        </div>
    </div>
</div>
{% endblock body %}

store/templates/store/empty_cart.html
{% extends 'store/base.html' %}
{% load static %}

{% block body %}

<br>
<div class="row my-4">
    <h3 class="text-center mb-4">You have no product in your cart</h3>
    <div class="text-center">
        <img src="{% static 'images/shopping-cart.jpg' %}" class="img-fluid img-thumbnail w-25">
    </div>
    <div class="text-center mt-4">
        <a href="{% url 'customer-products-view' %}" class="btn btn-info btn-lg">Continue Shopping</a>
    </div>
</div>

{% endblock body %}

store/templates/store/profile.html
{% extends 'store/profile_sidebar.html' %}
{% load crispy_forms_tags %}
{% block profileactive %} active {% endblock profileactive %}

{% block profile %}
<div class="col-md-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    <div class="card card-body">
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            <div class="mb-3 fs-4">
                <strong>Update Profile</strong>
                <hr>
            </div>
            <div class="mb-4">
                {{ user_update_form|crispy }}
            </div>
            <div class="mb-4">
                {{ customer_update_form|crispy }}
            </div>

            <div class="d-grid">
                <button type="submit" class="btn btn-primary"><b>Update Information</b></button>
            </div>
        </form>
    </div>
</div>

<div class="col-md-3">
    <div class="card card-body">
        <h3 style="text-align: center;">Profile Picture</h3>
        <hr>
        <img class="profile-pic" src="{{ request.user.customer.profile_pic.url }}">
    </div>
</div>
{% endblock profile %}

store/templates/store/profile_sidebar.html
{% extends 'store/base.html' %}
{% load static %}

{% block body %}
<br>
<div class="row my-4 profile">
    <div class="col-md-3">
        <div class="list-group">
            <span class="list-group-item settings-header">Account Settings</span>
            <a href="{% url 'profile' %}"
               class="{% block profileactive %} {% endblock profileactive %}">
                Profile Settings</a>
            <a href="{% url 'password_change' %}"
               class="{% block passwordactive %} {% endblock passwordactive %}">
                Change Password</a>
        </div>
    </div>

    {% block profile %}  {% endblock profile %}
</div>
{% endblock body %}

store/templates/store/send_feedback.html
{% extends 'store/base.html' %}
{% load static %}

{% block body %}
<br>
<div class="row my-4 justify-content-center">
    <div class="col-md-6">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        <div class="card card-body">
            <h4 class='alert alert-info text-center'>Send Us Your Valuable Feedback !</h4>

            <form action="" method="post"> {% csrf_token %}
                <div class="form-group mt-3">
                    {{ form.name.label }}
                    {{ form.name }}
                </div>

                <div class="form-group mt-3">
                    {{ form.feedback.label }}
                    {{ form.feedback }}
                </div>

                <div class="text-center mt-3">
                    <button type="submit" class="btn btn-info"><strong>Send Feedback</strong></button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock body %}

store/templates/store/view_feedbacks.html
{% extends 'store/base.html' %}
{% load static %}

{% block body %}
<br>
<div class="row my-4 justify-content-center">
    <div class="col-md-8">
        <div class="box-element shadow mb-4">

            <table class="table table-info table-striped table-hover border">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Sender</th>
                        <th scope="col">Feedback</th>
                        <th scope="col">Data Sent</th>
                    </tr>
                </thead>
                <tbody>
                    {% for feedback in feedbacks %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ feedback.name }}</td>
                        <td>{{ feedback.feedback }}</td>
                        <td>{{ feedback.created }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock body %}